public with sharing class MultiWrapes {

    public Wopty opty { get; set; }

    public void optys() {
    if(opp.stagename=='close won'){
     opp.closedate=system.today();
     }else{opp.closedate=system.today()+15;}

        
    }


    public String accs { get; set; }
    
    public Wrapper1 acc {set;get;}
    
    public WOpty opp {set;get;}
    
    public void accs() {
    if(acc.industry=='Banking'){
 acc.rating='Hot';
 } else {acc.rating='cold';}

        
    }
    
    public MultiWrapes ()
    {
    acc = new Wrapper1 ();
    opp = new Wopty ();
    }
    
}